baseURL = 'http://example.org/'
title = 'such as IT is'

# language
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true

baseurl = "/"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme="archie"
copyright = "© Aquila Minakami"

paginate = 5

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=true
	subtitle = "all articles are written by Aquila Minakami"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/yiegle"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/such_as_it_is/"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4